server:
  port: 8082

spring:
  application:
    name: MENU-SERVICE

  datasource:
    url: jdbc:mysql://catering-mysql:3306/menu_db
    username: root
    password: Prakash@3839

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://catering-service-registry:8761/eureka